# 测试环境的配置文件
server:
  port: 8281

# 指定mysql地址到windows主机的mysql
spring:
  datasource:
    url: jdbc:mysql://192.168.43.192:3306/atstudy_mall?useUnicode=true&characterEncoding=utf8
# 指定bootadmin的监控server地址，到windows主机
  boot:
    admin:
      client:
        url: http://192.168.43.192:8082
